# get http://yjh.li-shang-bin.com/iweb/topic/myTopicList?page=1
# Content-Type: application/json

# {
#   "user_id": "user8",
#   "token": "5c62dcb16e33b0f16c075627cbcc15dd"
# }

# post http://www.ftusix.com/static/data/topicList.php
# Content-Type: application/json

# {
#   "type":"0",
#   "sort":"new",
#   "page":"",
#   "index":"false"
# }

//get http://yjh.li-shang-bin.com/iweb/topic/topicList?par=&tech_type=1

# post http://www.ftusix.com/static/data/content.php
# Content-Type: application/json

# {
#   "user_id":"2",
#   "topic_id":"52"
# }

# post http://www.ftusix.com/static/data/sendsms.php
# Content-Type: application/json

# {
# "user_id": "user8",
# "page": "1"
# }

# get http://vue.tyqprivateweb.cn:35002/vue/article.php 
# Content-Type: application/json

# {
#   "event":"selectArticleList",
#   "kind":"hot",
#   "timestep":"1529387803",
#   "random":"5"
# }

# post http://www.ftusix.com/static/data/myNote.php
# Content-Type: application/x-www-form-urlencoded;charset=UTF-8

# {
#   "user_id":"186",
#   "page":"1"
# }

# get http://www.ftusix.com/static/data/myNote.php
# Content-Type: application/json

# {
#   "user_id":"186",
#   "page":"1"
# }

//get http://www.ftusix.com/static/data/content.php?user_id=186&topic_id=371

# post http://www.ftusix.com/static/data/zan.php
# Content-Type: application/json

# {
#   "user_id":"1",
#   "topic_id":"371",
#   "type":"zan"
# }

//get http://www.ftusix.com/static/data/myColl.php?user_id=186&page=1


# get http://www.ftusix.com/static/data/commentList.php?topic_id=371

post http://www.ftusix.com/static/data/topicList.php?type=0&sort=hot&page=1&index=true
